=== pawcoding/RandomSaber/packs/.pack.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/pawcoding/RandomSaber/angular_setup/packs/pack.schema.json",
  "type": "object",
  "default": {},
  "title": "Music Pack Schema",
  "required": [
    "id",
    "title",
    "type",
    "img",
    "songs"
  ],
  "properties": {
    "id": {
      "type": "string",
      "title": "The packs unique ID"
    },
    "title": {
      "type": "string",
      "title": "The title of the music pack / mixtape"
    },
    "type": {
      "type": "string",
      "default": "ADDON",
      "title": "The type of the pack",
      "enum": ["OST", "ADDON", "CUSTOM"]
    },
    "img": {
      "type": "string",
      "title": "The url to the cover art of the pack"
    },
    "songs": {
      "type": "array",
      "title": "List of all songs from this pack",
      "items": {
        "type": "object",
        "title": "Song",
        "required": [
          "title",
          "modes"
        ],
        "properties": {
          "title": {
            "type": "string",
            "title": "Song title"
          },
          "modes": {
            "type": "object",
            "title": "List of all modes including playable difficulties",
            "required": [
              "twoSabers",
              "oneSaber",
              "noArrows",
              "full",
              "quarter"
            ],
            "properties": {
              "twoSabers": {
                "type": "integer",
                "title": "Playable difficulties with two sabers"
              },
              "oneSaber": {
                "type": "integer",
                "title": "Playable difficulties with one saber"
              },
              "noArrows": {
                "type": "integer",
                "title": "Playable difficulties with no arrows"
              },
              "full": {
                "type": "integer",
                "title": "Playable difficulties with 360° view"
              },
              "quarter": {
                "type": "integer",
                "title": "Playable difficulties with 90° view"
              }
            }
          }
        }
      }
    }
  }
}

=== pawcoding/RandomSaber/packs/rocket.json
{
  "$schema": "https://raw.githubusercontent.com/pawcoding/RandomSaber/main/packs/.pack.schema.json",
  "id": "rocket",
  "title": "Rocket League Ã— Monstercat",
  "type": "ADDON",
  "img": "https://beatsaber.com/images/music/music6.jpg",
  "songs": [
    {
      "title": "Glide",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 10000,
        "quarter": 10000
      }
    },
    {
      "title": "LUV U NEED U",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 100,
        "quarter": 100
      }
    },
    {
      "title": "PLAY",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 11010,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "ROCK IT",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Shiawese",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Test Me",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    }
  ]
}

=== pawcoding/RandomSaber/packs/timbaland.json
{
  "id": "timbaland",
  "title": "Timbaland",
  "type": "ADDON",
  "img": "https://beatsaber.com/images/music/music8.jpg",
  "songs": [
    {
      "title": "Dumb Thingz",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Famous",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Has A Meaning",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 100,
        "quarter": 100
      }
    },
    {
      "title": "What I Like",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "While We're Young",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 11010,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    }
  ]
}

=== pawcoding/RandomSaber/packs/lizzo.json
{
  "$schema": "https://raw.githubusercontent.com/pawcoding/RandomSaber/main/packs/.pack.schema.json",
  "id": "lizzo",
  "title": "Lizzo",
  "type": "ADDON",
  "img": "https://beatsaber.com/images/music/music19.jpg",
  "songs": [
    {
      "title": "2 Be Loved",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "About Damn Time",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Cuz I Love You",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Everybody's Gay",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Good As Hell",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Juice",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Tempo",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Truth Hurts",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Worship",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    }
  ]
}

=== pawcoding/RandomSaber/packs/ost1.json
{
  "$schema": "https://raw.githubusercontent.com/pawcoding/RandomSaber/main/packs/.pack.schema.json",
  "id": "ost1",
  "title": "Original Soundtrack Vol. 1",
  "type": "OST",
  "img": "https://beatsaber.com/images/music/music1.jpg",
  "songs": [
    {
      "title": "$100 Bills",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 1000,
        "noArrows": 1111,
        "full": 10,
        "quarter": 10
      }
    },
    {
      "title": "Balearic Pumping",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 1000,
        "noArrows": 1111,
        "full": 10000,
        "quarter": 10000
      }
    },
    {
      "title": "Beat Saber",
      "modes": {
        "twoSabers": 1111,
        "oneSaber": 1000,
        "noArrows": 1111,
        "full": 1,
        "quarter": 1
      }
    },
    {
      "title": "Breezer",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 1000,
        "noArrows": 1111,
        "full": 10000,
        "quarter": 10000
      }
    },
    {
      "title": "Commercial Pumping",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 1000,
        "noArrows": 1111,
        "full": 10,
        "quarter": 10
      }
    },
    {
      "title": "Country Rounds",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 1000,
        "noArrows": 1111,
        "full": 1000,
        "quarter": 1000
      }
    },
    {
      "title": "Escape",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 1000,
        "noArrows": 1111,
        "full": 1000,
        "quarter": 1000
      }
    },
    {
      "title": "Legend",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 1000,
        "noArrows": 1111,
        "full": 100,
        "quarter": 100
      }
    },
    {
      "title": "Lvl Insane",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 1000,
        "noArrows": 1111,
        "full": 1000,
        "quarter": 1000
      }
    },
    {
      "title": "Turn Me On",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 1000,
        "noArrows": 1111,
        "full": 1,
        "quarter": 1
      }
    }
  ]
}

=== pawcoding/RandomSaber/packs/linkin.json
{
  "$schema": "https://raw.githubusercontent.com/pawcoding/RandomSaber/main/packs/.pack.schema.json",
  "id": "linkin",
  "title": "Linkin Park",
  "type": "ADDON",
  "img": "https://beatsaber.com/images/music/music9.jpg",
  "songs": [
    {
      "title": "Bleed It Out",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Breaking the Habit",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Faint",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Given Up",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "In the End",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "New Divide",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Numb",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "One Step Closer",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Papercut",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Somewhere I Belong",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "What I've Done",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    }
  ]
}

=== pawcoding/RandomSaber/packs/bts.json
{
  "$schema": "https://raw.githubusercontent.com/pawcoding/RandomSaber/angular_setup/packs/.pack.schema.json",
  "id": "bts",
  "title": "BTS",
  "type": "ADDON",
  "img": "https://beatsaber.com/images/music/music10.jpg",
  "songs": [
    {
      "title": "Blood Sweat & Tears",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Boy With Luv",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Burning Up",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Dionysus",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "DNA",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Dope",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Dynamite",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Fake Love",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "IDOL",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Mic Drop",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Not Today",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "UGH!",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    }
  ]
}

=== pawcoding/RandomSaber/packs/skrillex.json
{
  "$schema": "https://raw.githubusercontent.com/pawcoding/RandomSaber/angular_setup/packs/.pack.schema.json",
  "id": "skrillex",
  "title": "Skrillex",
  "type": "ADDON",
  "img": "https://beatsaber.com/images/music/music13.jpg",
  "songs": [
    {
      "title": "Bangerang",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Butterflies",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Don't Go",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "First of the Year",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Ragga Bomb",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Rock 'n' Roll",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Scary Monsters and Nice Spirits",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "The Devil's Den",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    }
  ]
}

=== pawcoding/RandomSaber/packs/ost3.json
{
  "$schema": "https://raw.githubusercontent.com/pawcoding/RandomSaber/angular_setup/packs/.pack.schema.json",
  "id": "ost3",
  "title": "Original Soundtrack Vol. 3",
  "type": "OST",
  "img": "https://beatsaber.com/images/music/OST3.jpg",
  "songs": [
    {
      "title": "Origins",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 11010,
        "noArrows": 0,
        "full": 11010,
        "quarter": 11010
      }
    },
    {
      "title": "Reason for Living",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 11010,
        "noArrows": 0,
        "full": 10000,
        "quarter": 10000
      }
    },
    {
      "title": "Give A Little Love",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Immortal",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 10,
        "quarter": 10
      }
    },
    {
      "title": "Full Charge",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Burning Sands",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    }
  ]
}
