=== pawcoding/RandomSaber/packs/.pack.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/pawcoding/RandomSaber/angular_setup/packs/pack.schema.json",
  "type": "object",
  "default": {},
  "title": "Music Pack Schema",
  "required": [
    "id",
    "title",
    "type",
    "img",
    "songs"
  ],
  "properties": {
    "id": {
      "type": "string",
      "title": "The packs unique ID"
    },
    "title": {
      "type": "string",
      "title": "The title of the music pack / mixtape"
    },
    "type": {
      "type": "string",
      "default": "ADDON",
      "title": "The type of the pack",
      "enum": ["OST", "ADDON", "CUSTOM"]
    },
    "img": {
      "type": "string",
      "title": "The url to the cover art of the pack"
    },
    "songs": {
      "type": "array",
      "title": "List of all songs from this pack",
      "items": {
        "type": "object",
        "title": "Song",
        "required": [
          "title",
          "modes"
        ],
        "properties": {
          "title": {
            "type": "string",
            "title": "Song title"
          },
          "modes": {
            "type": "object",
            "title": "List of all modes including playable difficulties",
            "required": [
              "twoSabers",
              "oneSaber",
              "noArrows",
              "full",
              "quarter"
            ],
            "properties": {
              "twoSabers": {
                "type": "integer",
                "title": "Playable difficulties with two sabers"
              },
              "oneSaber": {
                "type": "integer",
                "title": "Playable difficulties with one saber"
              },
              "noArrows": {
                "type": "integer",
                "title": "Playable difficulties with no arrows"
              },
              "full": {
                "type": "integer",
                "title": "Playable difficulties with 360° view"
              },
              "quarter": {
                "type": "integer",
                "title": "Playable difficulties with 90° view"
              }
            }
          }
        }
      }
    }
  }
}

=== pawcoding/RandomSaber/packs/camelia.json
{
  "$schema": "https://raw.githubusercontent.com/pawcoding/RandomSaber/main/packs/.pack.schema.json",
  "id": "camelia",
  "title": "Camelia",
  "type": "OST",
  "img": "https://static.wikia.nocookie.net/beat-saber/images/7/71/Camellia_Cover.jpg",
  "songs": [
    {
      "title": "Cycle Hit",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Crystallized",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "What the Cat?!",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Exit this Earth's Atmosphere",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "GHOST",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Light It Up",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    }
  ]
}

=== pawcoding/RandomSaber/packs/weeknd.json
{
  "$schema": "https://raw.githubusercontent.com/pawcoding/RandomSaber/main/packs/.pack.schema.json",
  "id": "weeknd",
  "title": "The Weeknd",
  "type": "ADDON",
  "img": "https://beatsaber.com/images/music/music20.jpg",
  "songs": [
    {
      "title": "Blinding Lights",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Can't Feel My Face",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "How Do I Make You Love Me?",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "I Feel It Coming",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Pray For Me",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Sacrifice",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Save Your Tears",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Starboy (feat. Daft Punk)",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Take My Breath",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "The Hills",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    }
  ]
}

=== pawcoding/RandomSaber/packs/gaga.json
{
  "$schema": "https://raw.githubusercontent.com/pawcoding/RandomSaber/main/packs/.pack.schema.json",
  "id": "gaga",
  "title": "Lady Gaga",
  "type": "ADDON",
  "img": "https://beatsaber.com/images/music/music15.jpg",
  "songs": [
    {
      "title": "Alejandro",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Bad Romance",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Born This Way",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Just Dance",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Paparazzi",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Poker Face",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Rain On Me",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Stupid Love",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Telephone",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "The Edge Of Glory",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    }
  ]
}

=== pawcoding/RandomSaber/packs/electronic.json
{
  "$schema": "https://raw.githubusercontent.com/pawcoding/RandomSaber/angular_setup/packs/.pack.schema.json",
  "id": "electronic",
  "title": "Electronic Mixtape",
  "type": "ADDON",
  "img": "https://beatsaber.com/images/music/music18.jpg",
  "songs": [
    {
      "title": "Alone",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Animals",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Freestyler",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Ghosts 'n' Stuff",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Icarus",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Sandstorm",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Stay The Night",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "The Rockafeller Skank",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Waiting All Night",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Witchcraft",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    }
  ]
}

=== pawcoding/RandomSaber/packs/rock.json
{
  "$schema": "https://raw.githubusercontent.com/pawcoding/RandomSaber/angular_setup/packs/.pack.schema.json",
  "id": "rock",
  "title": "Rock Mixtape",
  "type": "ADDON",
  "img": "https://beatsaber.com/images/music/music21.jpg",
  "songs": [
    {
      "title": "Born To Be Wild",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Eye of the Tiger",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Free Bird",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "I Was Made For Lovin' You",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Seven Nation Army",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Smells Like Teen Spirit",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Sweet Child O' Mine",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "The Pretender",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    }
  ]
}

=== pawcoding/RandomSaber/packs/extras.json
{
  "$schema": "https://raw.githubusercontent.com/pawcoding/RandomSaber/angular_setup/packs/.pack.schema.json",
  "id": "extras",
  "title": "Extras",
  "type": "OST",
  "img": "https://static.wikia.nocookie.net/beat-saber/images/2/23/Extras_Cover.png",
  "songs": [
    {
      "title": "Spooky Beat",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "FitBeat",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 1000,
        "noArrows": 0,
        "full": 1110,
        "quarter": 1000
      }
    },
    {
      "title": "Crab Rave",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 1000,
        "noArrows": 0,
        "full": 100,
        "quarter": 100
      }
    },
    {
      "title": "POP/STARS - K/DA",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 1000,
        "noArrows": 0,
        "full": 10000,
        "quarter": 10000
      }
    },
    {
      "title": "One Hope",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 1000,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Angel Voices",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 1000,
        "noArrows": 1111,
        "full": 0,
        "quarter": 0
      }
    }
  ]
}

=== pawcoding/RandomSaber/packs/interscope.json
{
  "$schema": "https://raw.githubusercontent.com/pawcoding/RandomSaber/angular_setup/packs/.pack.schema.json",
  "id": "interscope",
  "title": "Interscope Mixtape",
  "type": "ADDON",
  "img": "https://beatsaber.com/images/music/music12.jpg",
  "songs": [
    {
      "title": "Counting Stars",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "DNA.",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Don't Cha",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Party Rock Anthem",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Rollin' (Air Raid Vehicle)",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Sugar",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "The Sweet Escape",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    }
  ]
}

=== pawcoding/RandomSaber/packs/imagine.json
{
  "$schema": "https://raw.githubusercontent.com/pawcoding/RandomSaber/angular_setup/packs/.pack.schema.json",
  "id": "imagine",
  "title": "Imagine Dragons",
  "type": "ADDON",
  "img": "https://beatsaber.com/images/music/ID.jpg",
  "songs": [
    {
      "title": "Bad Liar",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Believer",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 11010,
        "noArrows": 0,
        "full": 110,
        "quarter": 110
      }
    },
    {
      "title": "Digital",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 1000,
        "quarter": 1000
      }
    },
    {
      "title": "It's Time",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Machine",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },{
      "title": "Natural",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },{
      "title": "Radioactive",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },{
      "title": "Thunder",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 11010,
        "noArrows": 0,
        "full": 100,
        "quarter": 100
      }
    },{
      "title": "Warriors",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },{
      "title": "Whatever It Takes",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    }
  ]
}
