=== pawcoding/RandomSaber/packs/.pack.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/pawcoding/RandomSaber/angular_setup/packs/pack.schema.json",
  "type": "object",
  "default": {},
  "title": "Music Pack Schema",
  "required": [
    "id",
    "title",
    "type",
    "img",
    "songs"
  ],
  "properties": {
    "id": {
      "type": "string",
      "title": "The packs unique ID"
    },
    "title": {
      "type": "string",
      "title": "The title of the music pack / mixtape"
    },
    "type": {
      "type": "string",
      "default": "ADDON",
      "title": "The type of the pack",
      "enum": ["OST", "ADDON", "CUSTOM"]
    },
    "img": {
      "type": "string",
      "title": "The url to the cover art of the pack"
    },
    "songs": {
      "type": "array",
      "title": "List of all songs from this pack",
      "items": {
        "type": "object",
        "title": "Song",
        "required": [
          "title",
          "modes"
        ],
        "properties": {
          "title": {
            "type": "string",
            "title": "Song title"
          },
          "modes": {
            "type": "object",
            "title": "List of all modes including playable difficulties",
            "required": [
              "twoSabers",
              "oneSaber",
              "noArrows",
              "full",
              "quarter"
            ],
            "properties": {
              "twoSabers": {
                "type": "integer",
                "title": "Playable difficulties with two sabers"
              },
              "oneSaber": {
                "type": "integer",
                "title": "Playable difficulties with one saber"
              },
              "noArrows": {
                "type": "integer",
                "title": "Playable difficulties with no arrows"
              },
              "full": {
                "type": "integer",
                "title": "Playable difficulties with 360° view"
              },
              "quarter": {
                "type": "integer",
                "title": "Playable difficulties with 90° view"
              }
            }
          }
        }
      }
    }
  }
}

=== pawcoding/RandomSaber/packs/ost5.json
{
  "id": "ost5",
  "title": "Original Soundtrack Vol. 5",
  "type": "OST",
  "img": "https://beatsaber.com/images/music/music16.jpg",
  "songs": [
    {
      "title": "$1.78",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Curtains (All Night Long)",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Final-Boss-Chan",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Firestarter",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "I Wanna Be A Machine",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Magic (ft. Meredith Bull)",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    }
  ]
}

=== pawcoding/RandomSaber/packs/billie.json
{
  "$schema": "https://raw.githubusercontent.com/pawcoding/RandomSaber/main/packs/.pack.schema.json",
  "id": "billie",
  "title": "Billie Eilish",
  "type": "ADDON",
  "img": "https://beatsaber.com/images/music/music14.jpg",
  "songs": [
    {
      "title": "all the good girls go to hell",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "bad guy",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "bellyache",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "bury a friend",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Happier Than Ever",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "I Didn't Change My Number",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "NDA",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Oxytocin",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Therefor I Am",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "you should see me in a crown",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    }
  ]
}

=== pawcoding/RandomSaber/packs/green.json
{
  "$schema": "https://raw.githubusercontent.com/pawcoding/RandomSaber/main/packs/.pack.schema.json",
  "id": "green",
  "title": "Green Day",
  "type": "ADDON",
  "img": "https://beatsaber.com/images/music/music7.jpg",
  "songs": [
    {
      "title": "American Idiot",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 11010,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Boulevard of Broken Dreams",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Father of All...",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 10,
        "quarter": 10
      }
    },
    {
      "title": "Holiday",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 100,
        "quarter": 100
      }
    },
    {
      "title": "Fire, Ready, Aim",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 1000,
        "quarter": 1000
      }
    },
    {
      "title": "Minority",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    }
  ]
}

=== pawcoding/RandomSaber/packs/ost4.json
{
  "id": "ost4",
  "title": "Original Soundtrack Vol. 4",
  "type": "OST",
  "img": "https://beatsaber.com/images/music/music11.jpg",
  "songs": [
    {
      "title": "Into The Dream",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "It Takes Me",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "LUDICROUS+",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Spin Eternally",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    }
  ]
}

=== pawcoding/RandomSaber/packs/panic.json
{
  "id": "panic",
  "title": "Panic! At The Disco",
  "type": "ADDON",
  "img": "https://beatsaber.com/images/music/music5.jpg",
  "songs": [
    {
      "title": "Emporer's New Clothes",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 1000,
        "quarter": 1000
      }
    },
    {
      "title": "The Greatest Show",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 100,
        "quarter": 100
      }
    },
    {
      "title": "High Hopes",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 11010,
        "noArrows": 0,
        "full": 100,
        "quarter": 100
      }
    },
    {
      "title": "Victorious",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    }
  ]
}

=== pawcoding/RandomSaber/packs/ost2.json
{
  "$schema": "https://raw.githubusercontent.com/pawcoding/RandomSaber/angular_setup/packs/.pack.schema.json",
  "id": "ost2",
  "title": "Original Soundtrack Vol. 2",
  "type": "OST",
  "img": "https://beatsaber.com/images/music/music2.jpg",
  "songs": [
    {
      "title": "Unlimited Power",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 11010,
        "noArrows": 1111,
        "full": 1000,
        "quarter": 1000
      }
    },
    {
      "title": "Rum n' Bass",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 1000,
        "noArrows": 1111,
        "full": 10000,
        "quarter": 10000
      }
    },
    {
      "title": "Be There For You",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 1000,
        "noArrows": 1111,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Elixia",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 1000,
        "noArrows": 1111,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "I Need You",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 1000,
        "noArrows": 1111,
        "full": 1,
        "quarter": 1
      }
    }
  ]
}

=== pawcoding/RandomSaber/packs/monstercat.json
{
  "$schema": "https://raw.githubusercontent.com/pawcoding/RandomSaber/main/packs/.pack.schema.json",
  "id": "monstercat",
  "title": "Monstercat",
  "type": "ADDON",
  "img": "https://beatsaber.com/images/music/music4.jpg",
  "songs": [
    {
      "title": "Boundless",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Emoji VIP",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Epic",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 1000,
        "quarter": 1000
      }
    },
    {
      "title": "Feeling Stronger",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Overkill",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 10000,
        "quarter": 10000
      }
    },{
      "title": "Rattlesnake",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 10000,
        "quarter": 10000
      }
    },{
      "title": "Stronger",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },{
      "title": "This Time",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 11010,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },{
      "title": "Till It's Over",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 1,
        "quarter": 1
      }
    },{
      "title": "We Won't Be Alone",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    }
  ]
}

=== pawcoding/RandomSaber/packs/fall.json
{
  "$schema": "https://raw.githubusercontent.com/pawcoding/RandomSaber/main/packs/.pack.schema.json",
  "id": "fall",
  "title": "Fall Out Boy",
  "type": "ADDON",
  "img": "https://beatsaber.com/images/music/music17.jpg",
  "songs": [
    {
      "title": "Centuries",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Dance, Dance",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "I Don't Care",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Immortals",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Irresistible",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "My Songs Know What You Did In The Dark",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "This Ain't A Scene, It's An Arms Race",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    },
    {
      "title": "Thnks fr th Mmrs",
      "modes": {
        "twoSabers": 11111,
        "oneSaber": 0,
        "noArrows": 0,
        "full": 0,
        "quarter": 0
      }
    }
  ]
}
